### ISSUE TITLE
full node not syncing 

### ISSUE THREAD

**Issue by b0atman** [Joystream/substrate-runtime-joystream#56]
OS: windows 10
launched using power shell: .\joystream-node.exe

result: node stopped syncing at block 222728

expected outcome: the finalized and best number should be going up and sync with the target number of blocks

![image](https://user-images.githubusercontent.com/50300732/57197730-cc6c1d80-6f38-11e9-82c9-58f2bf335c19.png)

Monero address: 42iysuonzWwezJLAtaB8sPT8RXWQGwg9UKkwAgG8oBpH88hYBZ6HtnieQwcDejtbTd9tjnkN46w2r4DdC18YjRWh6sjTjKs

**Comment by bwhm** [comment]
Hey @b0atman,

Thanks for reporting this. My guess is that your 6 peers and yourself forked off yesterday. This happens sometimes due to this [issue](https://github.com/Joystream/substrate-node-joystream/issues/68).

It looks like you are back in sync? In addition to increasing the peer count, restarting the node a couple of times each week or so should also help...

Unfortunately, this doesn't qualify for a bounty, but we hope you will continue reporting issues like this.
